name: Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build-deb:
    name: Build deb package
    strategy:
      matrix:
        docker_image:
          - "ubuntu:focal"
          - "ubuntu:bionic"
          - "ubuntu:xenial"
          - "debian:buster"
          - "debian:stretch"
        include:
          - docker_image: "ubuntu:focal"
            dist: focal
            arch: amd64
          - docker_image: "ubuntu:bionic"
            dist: bionic
            arch: amd64
          - docker_image: "ubuntu:xenial"
            dist: xenial
            arch: amd64
          - docker_image: "debian:buster"
            dist: buster
            arch: amd64
          - docker_image: "debian:stretch"
            dist: stretch
            arch: amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build deb package
        run: |
             tools/build-deb-with-docker.sh \
               ${{matrix.docker_image}} \
               ${{matrix.dist}} ${{matrix.arch}}
      - name: Upload deb package
        uses: actions/upload-artifact@v2
        with:
          path: "*.deb"
  build-hello-world-app:
    name: Build hello world app
    needs: build-deb
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Download deb packages
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Setup
        shell: bash
        run: |
          sudo dpkg -i artifacts/*/*focal*.deb && \
          tools/setup-palm-os-sdk.sh && \
          sudo palmdev-prep -d sdk-5r3
      - name: Build hello world app
        shell: bash
        run: tools/hello-world-app/build.sh
      - name: Upload hello world app
        uses: actions/upload-artifact@v2
        with:
          path: tools/hello-world-app/build/hello.prc

